__title__ = '{{ cookiecutter.project_name }}'
__package_name__ = '{{ cookiecutter.repo_name }}'
__author__ = '{{ cookiecutter.full_name }}'
__description__ = '{{ cookiecutter.project_short_description }}'
__email__ = '{{ cookiecutter.email }}'
__version__ = '{{ cookiecutter.version }}'
__license__ = '{{ cookiecutter.license }}'
__copyright__ = 'Copyright {{ cookiecutter.year }} {{ cookiecutter.full_name }}'
