# Config file for automatic testing at travis-ci.org

language: python

if: (type = push AND branch IN (master)) OR (type = pull_request)

python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test
